name: CD – Rakenna ja julkaise .exe ilman manuaalista tagia

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Build .exe with PyInstaller
        run: |
          pyinstaller --onefile matopeli.py

      - name: Create auto tag if missing
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a auto-latest -m "Automaattinen julkaisu"
          git push origin auto-latest

      - name: Upload .exe to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: Automaattinen julkaisu
          tag_name: auto-latest
          files: dist/matopeli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

