name: Matopeli CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Hae koodi GitHubista
      uses: actions/checkout@v3

    - name: Asenna Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Asenna riippuvuudet
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Suorita testit
      run: |
        pytest --cov=. --cov-report=html

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: htmlcov
